<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <parent>
    <groupId>io.enmasse</groupId>
    <artifactId>enmasse</artifactId>
    <version>0.34-SNAPSHOT</version>
  </parent>
  <packaging>pom</packaging>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>controller-manager</artifactId>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>prepare-controller-manager-dir</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <mkdir dir="${project.basedir}/build" />
              </target>
            </configuration>
          </execution>
          <execution>
            <id>generate-operator-image-map</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <mkdir dir="${project.basedir}/build" />
                <echo file="${project.basedir}/build/operatorImageMap.yaml">address-space-controller: ${ADDRESS_SPACE_CONTROLLER_IMAGE}
controller-manager: ${CONTROLLER_MANAGER_IMAGE}
router: ${ROUTER_IMAGE}
none-authservice: ${NONE_AUTHSERVICE_IMAGE}
keycloak: ${KEYCLOAK_IMAGE}
keycloak-plugin: ${KEYCLOAK_PLUGIN_IMAGE}
console-init: ${CONSOLE_INIT_IMAGE}
console-server: ${CONSOLE_SERVER_IMAGE}
console-proxy-openshift: ${CONSOLE_PROXY_OPENSHIFT_IMAGE}
console-proxy-openshift3: ${CONSOLE_PROXY_OPENSHIFT3_IMAGE}
console-proxy-kubernetes: ${CONSOLE_PROXY_KUBERNETES_IMAGE}
standard-controller: ${STANDARD_CONTROLLER_IMAGE}
agent: ${AGENT_IMAGE}
broker: ${BROKER_IMAGE}
broker-plugin: ${BROKER_PLUGIN_IMAGE}
topic-forwarder: ${TOPIC_FORWARDER_IMAGE}
</echo>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>${exec-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>build-controller-manager</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <workingDirectory>${maven.multiModuleProjectDirectory}</workingDirectory>
              <executable>go</executable>
              <environmentVariables>
                <GO111MODULE>on</GO111MODULE>
              </environmentVariables>
              <arguments>
                <argument>build</argument>
                <argument>-o</argument>
                <argument>${project.basedir}/build/controller-manager</argument>
                <argument>${maven.multiModuleProjectDirectory}/cmd/controller-manager</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>dist</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <ignoreMissingDescriptor>false</ignoreMissingDescriptor>
              <descriptors>
                <descriptor>src/assembly/unix-dist.xml</descriptor>
              </descriptors>
              <tarLongFileMode>posix</tarLongFileMode>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
